name: Terraform CI

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Run terraform fmt
        run: terraform fmt -recursive -check

      - name: Run terraform validate
        run: terraform validate
